global:
  image: node:18

  trigger:
    branch:
      - "*"

  environment:
    APP_ENV: production

jobs:

  - name: Install Dependencies
    commands:
      - npm ci
    artifacts:
      - name: node_modules
        path: ./node_modules/

  - name: Lint and generate docs
    commands:
      - npm run eslint
      - npm run prettier
      - npm run generate
    resources:
      - name: node_modules
        path: ./
    artifacts:
      - name: dist
        path: ./dist/

  - name: ditribute
    commands:
      - npm run upload
    resources:
      - name: dist
        path: ./
